<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FoodWise</title>
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 20px;
    color: #000;
    transition: 0.5s;
    animation: pulseLight 6s infinite;
  }

  .dark {
    animation: pulseDark 6s infinite;
    background-color: #2b2b2b;
    color: #000;
  }

  h1 { text-align: center; color: #ff66a3; }
  @keyframes pulseLight {
    0% { background-color: #ffe6f0; }
    50% { background-color: #d1a3ff; }
    100% { background-color: #ffe6f0; }
  }
  @keyframes pulseDark {
    0% { background-color: #000; }
    50% { background-color: #003366; }
    100% { background-color: #000; }
  }

  .card { background: #f2f2f2; padding: 20px; margin: 15px auto; max-width: 500px; border-radius: 10px; }
  input, button { padding: 10px; margin: 5px 0; font-size: 14px; }
  button { background-color: #ff66a3; color: #fff; border: none; cursor: pointer; }
  .item { margin: 5px 0; padding: 10px; border-radius: 5px; color: #fff; }
  .fresh { background-color: green; }
  .soon { background-color: orange; }
  .expired { background-color: red; }
</style>
</head>
<body>

<h1>FoodWise</h1>
<button onclick="document.body.classList.toggle('dark')">Toggle Dark Mode</button>

<div class="card">
  <h3>Add Food Item</h3>
  <input id="name" placeholder="Food name" type="text">
  <input id="date" type="date">
  <button onclick="add()">Add Item</button>
  <div id="list"></div>
  <p id="addFeedback" style="color:black;"></p>
</div>

<div class="card">
  <h3>Saved Food Impact</h3>
  <p id="impact">No items yet.</p>
</div>

<div class="card">
  <h3>Healthy Food Game</h3>
  <p id="foodEmoji" style="font-size: 2rem;">🍎</p>
  <button onclick="guess(true)">Healthy</button>
  <button onclick="guess(false)">Unhealthy</button>
  <p>Score: <span id="score">0</span></p>
  <p id="feedback" style="color:black;"></p>
</div>

<div class="card">
  <h3>Tap Challenge</h3>
  <button id="tapButton">Tap Me Fast!</button>
  <p id="tapResult"></p>
  <p id="tapFeedback" style="color:black;"></p>
</div>

<div class="card">
  <h3>Save Food Tips</h3>
  <ul>
    <li>📅 Plan meals ahead</li>
    <li>🧊 Freeze leftovers</li>
    <li>📦 Label and date food</li>
    <li>🥫 Use older items first</li>
    <li>🤝 <a href="https://www.google.com/maps/search/food+shelter+near+McKinney+TX" target="_blank">Find nearby food shelters</a></li>
  </ul>
</div>

<script>
let pantry = [];
let foods = [
  { emoji: "🍎", healthy: true },
  { emoji: "🍩", healthy: false },
  { emoji: "🥦", healthy: true },
  { emoji: "🍕", healthy: false }
];
let current = {};
let score = 0;
let taps = 0;
let tapping = false;

function add() {
  let n = document.getElementById('name').value.trim();
  let d = document.getElementById('date').value;
  if (!n || !d) return;
  pantry.push({ name: n, date: d });
  document.getElementById('name').value = '';
  document.getElementById('date').value = '';
  showPantry();
  document.getElementById('addFeedback').innerText = "Nice job! You added a food item!";
}

function showPantry() {
  let list = document.getElementById('list');
  list.innerHTML = '';
  let savedCount = 0;
  pantry.forEach((f, i) => {
    let days = Math.ceil((new Date(f.date) - new Date()) / (1000*60*60*24));
    let status = days < 0 ? 'expired' : days < 3 ? 'soon' : 'fresh';
    if(days >= 0) savedCount++;
    let div = document.createElement('div');
    div.className = 'item ' + status;
    div.innerHTML = `${f.name} (${days} days) <button onclick="deleteItem(${i})">Delete</button>`;
    list.appendChild(div);
  });
  document.getElementById('impact').innerText = `Saved ${savedCount} items (~${(savedCount*1.6).toFixed(1)} lbs, ~$${(savedCount*4.5).toFixed(2)}, ~${(savedCount*1.6*3.2).toFixed(1)} lbs CO₂)`;
}

function deleteItem(i) {
  pantry.splice(i, 1);
  showPantry();
  document.getElementById('addFeedback').innerText = "You removed an item! Keep going!";
}

// Healthy Food Game
function nextFood() {
  current = foods[Math.floor(Math.random() * foods.length)];
  document.getElementById('foodEmoji').innerText = current.emoji;
  document.getElementById('feedback').innerText = '';
}

function guess(isHealthy) {
  if (isHealthy === current.healthy) {
    score++;
    document.getElementById('feedback').innerText = 'Correct! Great job!';
  } else {
    score--;
    document.getElementById('feedback').innerText = 'Oops! Try again!';
  }
  document.getElementById('score').innerText = score;
  nextFood();
}

// Tap Challenge
document.getElementById('tapButton').addEventListener('click', function() {
  if (!tapping) {
    taps = 0;
    tapping = true;
    this.innerText = 'Go! Tap Fast!';
    let btn = this;
    let clickHandler = function() { taps++; };
    btn.addEventListener('click', clickHandler);
    setTimeout(() => {
      tapping = false;
      btn.removeEventListener('click', clickHandler);
      btn.innerText = 'Tap Me Fast!';
      document.getElementById('tapResult').innerText = `You tapped ${taps} times!`;
      document.getElementById('tapFeedback').innerText = "Nice! Keep practicing!";
    }, 5000);
  }
});

showPantry();
nextFood();
</script>

</body>
</html>
